SweetHome/SweetHome/Models/About.cs
namespace SweetHome.Models
{
    public class About
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
    }
}

SweetHome/SweetHome/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace SweetHome.Models
{
    public class AppUser:IdentityUser
    {
        public string? FullName { get; set; }
        public bool IsAgent { get; set; } =false;
        public string? Image { get; set; }
        public List<Order>? Orders { get; set; }
        public List<Comment>? Comments { get; set; }

    }
}

SweetHome/SweetHome/Models/Category.cs
namespace SweetHome.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public List<Product>? Products { get; set; }
    }
}

SweetHome/SweetHome/Models/City.cs
namespace SweetHome.Models
{
    public class City
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public List<Product>? Products{ get; set; }
    }
}

SweetHome/SweetHome/Models/Comment.cs
namespace SweetHome.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public DateTime? Date { get; set; }
        public AppUser? ApplicationUser { get; set; }
        public string AppUserId { get; set; }
        public Product? Product { get; set; }
        public int ProductId { get; set; }
    }
}

SweetHome/SweetHome/Models/Contact.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SweetHome.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public string? Name { get; set; }
        public string? Title { get; set; }
        public string? Desc { get; set; }

    }
}

SweetHome/SweetHome/Models/Faq.cs
namespace SweetHome.Models
{
    public class Faq
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public string Description { get; set; } 
    }
}

SweetHome/SweetHome/Models/HomeType.cs
namespace SweetHome.Models
{
    public class HomeType
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public List<Product>? Products{ get; set; }
    }
}

SweetHome/SweetHome/Models/Order.cs
namespace SweetHome.Models
{
    public class Order
    {
        public int Id { get; set; }
        public AppUser? AppUser { get; set; }
        public string? AppUserId { get; set; }
        public bool? Status { get; set; }
        public int? ProductId { get; set; }
        public Product? Product { get; set; }
        public string? ProductName { get; set; } 
        public decimal Price { get; set; }
        public int? TeamId { get; set; }
        public Team? Team { get; set; }
        public DateTime PurchasedAt { get; set; }
    }
}

SweetHome/SweetHome/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SweetHome.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Room { get; set; }
        public decimal Price { get; set; }
        public int HomeSize { get; set; }
        public int? TeamId { get; set; }
        public Team? Team { get; set; }
        public bool IsDeleted { get; set; }=false;
        public int StatusId { get; set; }
        public Status? Status { get; set; }  
        public int CityId { get; set; }
        public City? City { get; set; }
        public int HomeTypeId { get; set; }
        public HomeType? HomeType { get; set; }
        public ICollection<ProductImage>? ProductImages { get; set; }
        public int CategoryId { get; set; }
        public Category? Category { get; set; }
        [NotMapped]
        public IFormFile? ImageMain { get; set; } 
        [NotMapped]
        public List<IFormFile>? Files { get; set; }
        public List<Order>? Orders { get; set; }
        public List<Comment>? Comments { get; set; }

    }
}

SweetHome/SweetHome/Models/ProductImage.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SweetHome.Models
{
    public class ProductImage
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public bool IsMain { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public int ProductId { get; set; }
        public Product? Product { get; set; }
    }
}

SweetHome/SweetHome/Models/Settings.cs
namespace SweetHome.Models
{
    public class Settings
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

SweetHome/SweetHome/Models/Slider.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SweetHome.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Icon { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

SweetHome/SweetHome/Models/Status.cs
namespace SweetHome.Models
{
    public class Status
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public List<Product>?Products { get; set; }
    }
}

SweetHome/SweetHome/Models/Team.cs
namespace SweetHome.Models
{
    public class Team
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Phone { get; set; }
        public string? Email { get; set; }
        public string? Image { get; set; }
        public List<Product>? Products{ get; set; }
        public List<Order>? Orders { get; set;}
    }
}

SweetHome/SweetHome/ViewModels/FilterVM.cs
using SweetHome.Models;

namespace SweetHome.ViewModels
{
    public class FilterVM
    {
        public List<Category> Categories { get; set; } = null!;
        public int? CategoryId { get; set; }
        public List<City> Citys { get; set; } = null!;
        public int? CityId { get; set; }
        public List<HomeType> HomeTypes { get; set; } = null!;
        public int? HomeTypeId { get; set; }
        public List<Product> Products { get; set; }=null!;
    }
}

SweetHome/SweetHome/ViewModels/HomeVM.cs
using SweetHome.Models;

namespace SweetHome.ViewModels
{
    public class HomeVM
    {
        public List<Slider>Sliders { get; set; }
        public List<Product> Products { get; set; }
        public List<About> Abouts { get; set; }
        public List<Team> Teams { get; set; }
    }
}

SweetHome/SweetHome/ViewModels/OrderVM.cs
using SweetHome.Models;

namespace SweetHome.ViewModels
{
    public class OrderVM
    {
        public Product? Products { get; set; }
    }
}

SweetHome/SweetHome/ViewModels/SearchVM.cs
using SweetHome.Models;

namespace SweetHome.ViewModels
{
    public class SearchVM
    {
        public string? ProdName { get; set; }
    }
}

SweetHome/SweetHome/ViewModels/SellerVM.cs
using SweetHome.Models;

namespace SweetHome.ViewModels
{
    public class SellerVM
    {
        public Team? Team { get; set; }
        public Product? Product { get;set; }
    }
}

SweetHome/SweetHome/ViewModels/UserVM.cs
using SweetHome.Models;

namespace SweetHome.ViewModels
{
    public class UserVM
    {
        public string UserName { get; set; }
        public string Phone { get;set; }
        public string Email { get; set; }
        public string Image { get;set; }
        public List<Product>? products { get; set; }

    }
}

SweetHome/SweetHome/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SweetHome.DAL;

namespace SweetHome.Controllers
{
    public class TeamController : Controller
    {
        private readonly AppDbContext _context;

        public TeamController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Teams.OrderByDescending(x=>x.Id).ToList());
        }
        public async Task<IActionResult> Detail(int id)
        {
            return View(await _context.Teams.FirstOrDefaultAsync(x=>x.Id== id));
        }
    }
}

SweetHome/SweetHome/Views/Team/Detail.cshtml
@using SweetHome.Models;
@model Team
<!-- BREADCRUMB AREA START -->
<div class="ltn__breadcrumb-area text-left bg-overlay-white-30 bg-image " data-bs-bg="img/bg/14.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ltn__breadcrumb-inner">
                    <h1 class="page-title">Agent Details</h1>
                    <div class="ltn__breadcrumb-list">
                        <ul>
                            <li><a asp-controller="Home" asp-action="Index"><span class="ltn__secondary-color"><i class="fas fa-home"></i></span> Home</a></li>
                            <li>Agent Details</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- BREADCRUMB AREA END -->
<!-- TEAM DETAILS AREA START -->
<div class="ltn__team-details-area mb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="ltn__team-details-member-info text-center mb-40">
                    <div class="team-details-img">
                        <img src="~/assets/img/team/@Model.Image" alt="Team Member Image">
                    </div>
                    <h2>@Model.Name</h2>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="ltn__team-details-member-info-details">
                    <div class="row">
                            <div class="ltn__team-details-member-about">
                                <ul>
                                    <li><strong>Email:</strong> @Model.Email</li>
                                    <li><strong>Fax:</strong> @Model.Phone</li>
                                    <li><strong>Phone:</strong> @Model.Phone</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
<!-- TEAM DETAILS AREA END -->

SweetHome/SweetHome/Views/Team/Index.cshtml
@using SweetHome.Models;
@model IEnumerable<Team>
 <!-- BREADCRUMB AREA START -->
<div class="ltn__breadcrumb-area text-left bg-overlay-white-30 bg-image " data-bs-bg="img/bg/14.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ltn__breadcrumb-inner">
                    <h1 class="page-title">Our Agent</h1>
                    <div class="ltn__breadcrumb-list">
                        <ul>
                            <li><a asp-controller="Home" asp-action="Index"><span class="ltn__secondary-color"><i class="fas fa-home"></i></span> Home</a></li>
                            <li>Agent</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- BREADCRUMB AREA END -->
<!-- TEAM AREA START (Team - 3) -->
<div class="ltn__team-area pt-110--- pb-90">
    <div class="container">
        <div class="row justify-content-center">
            @foreach(var item in Model){
            <div class="col-lg-4 col-sm-6">
                <div class="ltn__team-item ltn__team-item-3---">
                    <div class="team-img">
                        <img src="~/assets/img/team/@item.Image" alt="Image">
                    </div>
                    <div class="team-info">
                        <h4><a asp-controller="Team" asp-action="Detail" asp-route-id="@item.Id">@item.Name</a></h4>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>
<!-- TEAM AREA END -->